services:
    redis:
        image: redis
        container_name: redis
        restart: always
        ports:
            - "127.0.0.1:6379:6379"
        volumes:
            - redis_data:/data
    postgres:
        image: postgres:17
        container_name: postgres_db
        restart: always
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: kepegawaian
        ports:
            - "127.0.0.1:5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@email.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "127.0.0.1:5050:80"
        depends_on:
            - postgres
    adminer:
        image: adminer
        restart: always
        environment:
            ADMINER_DEFAULT_SERVER: postgres
        ports:
            - "127.0.0.1:8083:8080"
volumes:
    postgres_data:
    redis_data:
