services:
  # ---------------------------
  loki:
    image: grafana/loki:3
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    volumes:
      - loki-data:/loki

  promtail:
    image: grafana/promtail:3
    container_name: promtail
    user: "root"
    command: -config.file=/etc/promtail/promtail-config.yml
    volumes:
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes/lareact_storage-logs/_data:/var/log/laravel:ro
      - /var/lib/docker/volumes/lareact_php-logs/_data:/var/log/php:ro # ← baru
      - /var/lib/docker/volumes/lareact_nginx-logs/_data:/var/log/nginx:ro # ← baru
      - /var/lib/docker/volumes/lareact_supervisor-logs/_data:/var/log/supervisor:ro # ← NEW

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - "81:3000"
    volumes:
      # provisioning langsung ke folder bawaan Grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - grafana-data:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    environment:
      GF_SECURITY_ADMIN_USER: admin # → login = admin / admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      TZ: Asia/Jakarta
    depends_on:
      - loki

volumes:
  loki-data:
  grafana-data:
