server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
################################################################################
# 1. LARAVEL – storage/logs/laravel.log
################################################################################
  - job_name: laravel
    static_configs:
      - targets: [localhost]
        labels:
          job: laravel
          __path__: /var/log/laravel/*.log
    pipeline_stages:
      - regex:
          expression: '\[(?P<time>[^\]]+)\]\s(?P<env>\w+)\.(?P<level>\w+):\s(?P<msg>.*)'
      - timestamp:
          source: time
          format: '2006-01-02 15:04:05'
          location: Asia/Jakarta
      - labels:
          env:
          level:
      - output:
          source: msg

################################
  # ─── ORVA-BE – supervisor log via docker_sd ─────────────────────
  - job_name: orva-be-docker          # beda dari job lain
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 10s

    relabel_configs:
      # label konstan → mencegah stream kosong
      - target_label: job
        replacement: orva-be-docker
      - target_label: container
        replacement: orva-be
      # keep hanya kontainer bernama persis “orva-be”
      - source_labels: [__meta_docker_container_name]
        regex: '^/orva-be$'
        action: keep

    # Pipeline minimal: hanya pecah header json-file Docker
    pipeline_stages:
      - regex:
          # 2025-06-17T10:23:45.678901234Z stdout F log body…
          expression: '^(?P<time>[^ ]+)\s(?P<stream>stdout|stderr)\s[A-Z]\s(?P<msg>.*)'
      - timestamp:
          source: time
          format: RFC3339Nano
      - labels:
          stream:      # stdout / stderr
          container:
          job:
      - output:
          source: msg   # kirim isi apa adanya

  # ─── PHP-FPM – php8.1-fpm.log ───────────────────────────────────
  - job_name: php-fpm
    static_configs:
      - targets: [localhost]
        labels:
          job: php-fpm
          __path__: /var/log/php/php8.4-fpm.log   # kalau nama file berubah, ganti saja

    # Pipeline ringan: tarik waktu & level kalau ada, kirim sisanya mentah
    pipeline_stages:
      - regex:
          # [17-Jun-2025 05:23:14] WARNING: blah…
          expression: '\[(?P<time>\d{2}-\w{3}-\d{4}\s+\d{2}:\d{2}:\d{2})\]\s+(?:(?P<level>\w+):\s+)?(?P<msg>.*)'
      - timestamp:
          source: time
          format: '02-Jan-2006 15:04:05'
          location: Asia/Jakarta
      - labels:
          level:
      - output:
          source: msg

  ###############################################################################
  # NGINX – access.log
  ###############################################################################
  - job_name: nginx-access
    static_configs:
      - targets: [localhost]
        labels:
          job: nginx-access
          __path__: /var/log/nginx/access.log      # satu file saja

    pipeline_stages:
      # format combined log
      - regex:
          expression: '^(?P<remote>[^ ]+) [^ ]+ [^ ]+ \[(?P<time>[^\]]+)\] "(?P<method>[A-Z]+) (?P<uri>[^ ]+) [^"]+" (?P<status>\d{3}) (?P<size>\d+)'
      - timestamp:
          source: time
          format: '02/Jan/2006:15:04:05 -0700'
          location: Asia/Jakarta
      - labels:
          status:
          method:
      - output:
          source: uri          # simpan URI saja biar ringkas

  ###############################################################################
  # NGINX – error.log
  ###############################################################################
  - job_name: nginx-error
    static_configs:
      - targets: [localhost]
        labels:
          job: nginx-error
          __path__: /var/log/nginx/error.log

    pipeline_stages:
      - regex:
          expression: '^(?P<time>\d{4}/\d{2}/\d{2} \d{2}:\d{2}:\d{2}) \[(?P<level>\w+)\] [^:]+: (?P<msg>.*)'
      - timestamp:
          source: time
          format: '2006/01/02 15:04:05'
          location: Asia/Jakarta
      - labels:
          level:
      - output:
          source: msg

  # ─── SUPERVISOR – per-program & logtype ─────────────────────────
  - job_name: supervisor
    static_configs:
      - targets: [localhost]
        labels:
          job: supervisor
          __path__: /var/log/supervisor/*.log*    # aktif + rotate

    ###############################################################
    # 1) LABEL dari NAMA FILE
    ###############################################################
    relabel_configs:
      # program = bagian sebelum "-error.log" / ".log"
      - source_labels: [__path__]
        regex: '.*/([^/]+?)(?:-error)?\.log(?:-\d{4}-\d{2}-\d{2})?$'
        target_label: program
        action: replace

      # logtype = error  (hanya kalau nama file mengandung "-error.log")
      - source_labels: [__path__]
        regex: '.*/[^/]+?-error\.log(?:-\d{4}-\d{2}-\d{2})?$'
        target_label: logtype
        replacement: error
        action: replace

      # logtype = out    (default bila belum terisi)
      - source_labels: [logtype]
        regex: '^$'
        target_label: logtype
        replacement: out
        action: replace

    ###############################################################
    # 2) PIPELINE opsional – ambil timestamp & level
    ###############################################################
    pipeline_stages:
      - regex:
          expression: '^(?P<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})(?:,\d+)?\s+(?P<level>[A-Z]+)\s+(?P<msg>.*)'
      - timestamp:
          source: time
          format: '2006-01-02 15:04:05'
          location: Asia/Jakarta
      - labels:
          level:
          program:
          logtype:
      - output:
          source: msg
